networks:
  app-network:
    driver: bridge 

volumes:
  postgres_data:
  redis_data:

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - auth-service
      - vpn-service
      - tg-bot-service
    networks:
      - app-network
  
  db:
    image: postgres:15-alpine
    container_name : db
    hostname: postgres
    restart: unless-stopped 
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./docker-init-db:/docker-entrypoint-initdb.d
    healthcheck:                                
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d vpndb"]
      interval: 10s
      timeout: 5s
      retries: 5 
      start_period: 20s
    ports:
      - "5432:5432"
    networks:
      - app-network

  auth-service:
    build: .
    container_name: auth-service
    working_dir: /app/auth
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/auth:/app/auth
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: 
      sh -c 
      "
      sleep 5 &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8001
      "
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  vpn-service:
    build: .
    container_name: vpn-service
    working_dir: /app/vpn
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/vpn:/app/vpn
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: 
      sh -c
      "
      uvicorn main:app --host 0.0.0.0 --port 8002
      "
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  tg-bot-service:
    build: .
    container_name: tg-bot-service
    working_dir: /app/telegram_bot
    ports:
      - 8003:8003
    volumes:
      - ./services/telegram_bot:/app/telegram_bot
      - ./shared:/app/shared
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    command: 
      sh -c
      "
      uvicorn main:app --host 0.0.0.0 --port 8003
      "
    restart: unless-stopped
    networks:
      - app-network





  
